//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeliculasWindowsForms
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeliculasDetalle
    {
        public int IdPelicula { get; set; }
        public Nullable<int> IdCategoria { get; set; }
        public string Titulo { get; set; }
        public string Sipnosis { get; set; }
        public string Calificacion { get; set; }
        public string Ano { get; set; }
        public string Idioma { get; set; }
    }
}
